
// <?=$this->zmienna;
// echo "<br>";

// echo "guest view ", $this->acl->isAllowed('guest', null, 'view') ?
// "allowed" : "denied";
// // allowed

// echo "<br>";

// echo 'staff publish ', $this->acl->isAllowed('staff', null, 'publish') ?
// "allowed" : "denied";
// // denied

// echo "<br>";

// echo "staff revise ", $this->acl->isAllowed('staff', null, 'revise') ?
// "allowed" : "denied";
// // allowed

// echo "<br>";

// echo "editor view ", $this->acl->isAllowed('editor', null, 'view') ?
// "allowed" : "denied";
// // allowed because of inheritance from guest

// echo "<br>";

// echo "editor update ", $this->acl->isAllowed('editor', null, 'update') ?
// "allowed" : "denied";
// // denied because no allow rule for 'update'

// echo "<br>";

// echo "administrator view ", $this->acl->isAllowed('administrator', null, 'view') ?
// "allowed" : "denied";
// // allowed because administrator is allowed all privileges

// echo "<br>";

// echo "administrator ", $this->acl->isAllowed('administrator') ?
// "allowed" : "denied";
// // allowed because administrator is allowed all privileges

// echo "<br>";

// echo "administrator view ", $this->acl->isAllowed('administrator', null, 'update') ?
// "allowed" : "denied";
// // allowed because administrator is allowed all privileges

// echo "<br> Database: <BR>";

// try
// {
// 	$dbAdapter = Zend_Db_Table::getDefaultAdapter();
// } 
// catch (Zend_Db_Adapter_Exception $e) {
// 	// perhaps a failed login credential, or perhaps the RDBMS is not running
// 	echo 'Zend_Db_Table::getDefaultAdapter failed', ' ', $e->__toString();
// } 
// catch (Zend_Exception $e) {
// 	// perhaps factory() failed to load the specified Adapter class
// 	echo $e->__toString();	
// }

// $authAdapter = new Zend_Auth_Adapter_DbTable($dbAdapter);

// //$sql = $dbAdapter->getDbSelect();

// $select = $dbAdapter->select()->from('test');

// $sql = $dbAdapter->query($select);

// $result = $sql->fetchAll();

// // $stmt = $select->query($select);

// // // $result is an array of objects
//  var_dump($result);
 
//  $defaultNamespace = new Zend_Session_Namespace('Default');
 
//  if (isset($defaultNamespace->numberOfPageRequests)) {
//  	// this will increment for each page load.
//  	$defaultNamespace->numberOfPageRequests++;
//  } else {
//  	$defaultNamespace->numberOfPageRequests = 1; // first time
//  }
 
//  echo "Page requests this session: ".$defaultNamespace->numberOfPageRequests."<br>";
 
//  print_r($defaultNamespace);
 
  
 
//  //This is in your bootstrap, note you can also use Zend_Config in the constructor
//  $config = array(
//  		'name'           => 'sessions',      //table name as per Zend_Db_Table
//  		'primary'        => 'Session_ID',   //the sessionID given by php
//  		'modifiedColumn' => 'modified',     //time the session should expire
//  		'dataColumn'     => 'Session_data', //serialized data
//  		'lifetimeColumn' => 'lifetime'      //end of life for a specific record
//  );
//  $saveHandler = new Zend_Session_SaveHandler_DbTable($config);
//  //cookie persist for 30 days
//  Zend_Session::rememberMe($seconds = (60 * 60 * 24 * 30));
 
//  //make the session persist for 30 days
//  $saveHandler->setLifetime($seconds)->setOverrideLifetime(true);
//  //similarly,
//  //$saveHandler->setLifetime($seconds, true);
//  Zend_Session::setSaveHandler($saveHandler);
//  Zend_Session::start();

//?>

// <? // login/index.phtml ?>
<!-- <h2>Please Login</h2> -->
// <?= $this->form ?>
