<html>
<body>
			<div id="login_form_content" class="ajax_box">
				<div class="ajax_box_top"><h1 style="float:center;">LOGOWANIE</h1><div class="add_account" style="float:right;">REJESTRACJA</div></div>
				<div class="ajax_box_cont">
					<form class="login_form">
						<input name="login" type="text" value="E-mail">
						<input name="haslo" type="password" value="pass">
						<a href="javascript:void();" class="right remember_pass"><span id="przypomnij_haslo">Nie pamiętasz hasła ?</span></a>
						<input type="submit" class="orange_submit" value="ZALOGUJ SIĘ">
					</form>
				</div>
			</div>
</body>
</html>

<?php
